vim.cmd("set shell=pwsh")
require("muneeb.plugins.packer")
require("muneeb.plugins.dressing")
require("muneeb.plugins.telescope")
require("muneeb.plugins.neotree")
require("muneeb.plugins.mini")
require("muneeb.plugins.treesitter")
require("muneeb.plugins.colorscheme")
require("muneeb.plugins.lazygit")
