-- if true then return {} end
return {
  -- "rest-nvim/rest.nvim",
  -- ft = "http",
  -- event = "VeryLazy",
  -- dependencies = {
  --   "vhyrro/luarocks.nvim",
  --   priority = 1000,
  --   event = "VeryLazy",
  --   config = true,
  --   opts = {
  --     rocks = { "lua-curl", "nvim-nio", "mimetypes", "xml2lua" },
  --   },
  -- },
  -- keybinds = {
  --   {
  --     "<localleader>rr",
  --     "<Plug>RestNvim<cr>",
  --     "Run request under the cursor",
  --   },
  --   {
  --     "<localleader>rl",
  --     "<Plug>RestNvimLast<cr>",
  --     "Re-run latest request",
  --   },
  -- },
  -- config = function()
  --   require("rest-nvim").setup()
  -- end,
}
